# cloudbuild.yaml para usar Cloud Build -> Container Registry (ou Artifact Registry)
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.' ]
images:
- 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'